### ISSUE TITLE
Command Injection in setup.php

### ISSUE THREAD

**Issue by fbogner** [jenyraval/Phishing-Simulation#3]
Hi,

The HTTP Post parameter orgdomain in the file /AdminPanel/setup.php is used within a shell_exec call without sanitation. This can lead to command injection.

On Linux it is enough to set the parameter to _;whoami_
This leads to the following command line: python \AdminPanel\dnstwist-master\dnstwist.py --dictionary \AdminPanel\dnstwist-master\dictionaries\english.dict --format idle ;whoami

On Windows the || char should cause a similar behaviour.

The underlying issue is that htmlspecialchars does not encode ; nor || characters.
Maybe it would be a good idea to use a regex with valid characters? (whitelist)

This one looks pretty good: https://regex101.com/r/ZIMkXh/1
(source: https://stackoverflow.com/questions/3026957/how-to-validate-a-domain-name-using-regex-php)

**Comment by jenyraval** [comment]
Appreciate you time in reviewing!

Changes merged to master.
